apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-app
  labels:
    app: contacts-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contacts-app
  template: #pod defintion
    metadata:
      labels:
        app: contacts-app
    spec: # container specs
      containers:
        - name: contacts-app
          image: shashkist/flask-contacts-app
          ports:
            - containerPort: 5052
          env:
          - name: DB_HOST
            value: mysql-service
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            value: "admin"

---
apiVersion: v1
kind: Service
metadata:
 name: flask-contacts-service
spec:
 selector:
   app: contacts-app
 type: LoadBalancer # external service which can be accessed from outside the cluster
 ports:
   - name: flask-contacts-service 
     protocol: TCP
     port: 5000
     targetPort: 5052   
